# Generated by Django 5.0.4 on 2024-04-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
