# Generated by Django 5.0.4 on 2024-04-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0004_alter_movie_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_date", models.DateField(auto_now_add=True)),
                ("review_title", models.TextField()),
                ("review_content", models.TextField()),
                (
                    "review_movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.movie",
                        to_field="title",
                    ),
                ),
            ],
        ),
    ]
