# Generated by Django 5.0.4 on 2024-04-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="reviews.reviews",
            ),
        ),
    ]
